//! NCBI dbSNP via E-utilities. Seam: S3. 2-step.
use super::adapter::ProtocolAdapter; use super::fetch::{ParsedResponse, RetrievedRecord}; use crate::ScienceError;
pub fn esearch_path(term: &str, max: u32) -> String { format!("/esearch.fcgi?db=snp&retmode=json&retmax={max}&retstart=0&term={}", super::url_encode(term)) }
pub fn esummary_path(ids: &[String]) -> String { format!("/esummary.fcgi?db=snp&retmode=json&id={}", ids.join(",")) }
fn parse_esearch(bytes: &[u8]) -> crate::Result<Vec<String>> { let v: serde_json::Value = serde_json::from_slice(bytes)?; let list = v.pointer("/esearchresult/idlist").and_then(|l| l.as_array()).ok_or_else(|| ScienceError::Invalid("dbsnp: missing idlist".into()))?; Ok(list.iter().filter_map(|i| i.as_str().map(|s| s.to_owned())).collect()) }
fn parse_esummary(bytes: &[u8]) -> crate::Result<ParsedResponse> { let v: serde_json::Value = serde_json::from_slice(bytes)?; let r = v.get("result").ok_or_else(|| ScienceError::Invalid("dbsnp: missing result".into()))?; let uids = r.get("uids").and_then(|u| u.as_array()).ok_or_else(|| ScienceError::Invalid("missing uids".into()))?; let mut records = Vec::with_capacity(uids.len()); for uid in uids { let uid = uid.as_str().unwrap_or(""); if uid.is_empty() { continue; } if let Some(item) = r.get(uid) { let rs = item.get("snp_id").and_then(|s| s.as_u64()).map(|n| format!("rs{n}")).unwrap_or_else(|| uid.to_owned()); let chr = item.get("chr").and_then(|c| c.as_str()).unwrap_or(""); records.push(RetrievedRecord { id: uid.to_owned(), title: rs, container: format!("chr{chr}").trim().to_owned(), url: format!("https://www.ncbi.nlm.nih.gov/snp/{uid}") }); } } Ok(ParsedResponse { total_hits: records.len() as u64, records }) }
pub struct DbsnpAdapter;
impl ProtocolAdapter for DbsnpAdapter { fn descriptor(&self) -> &'static super::ConnectorDescriptor { &super::DBSNP } fn expected_exchanges(&self) -> usize { 2 } fn build_fixture_paths(&self, q: &str, m: u32, _f: &[Vec<u8>]) -> crate::Result<Vec<String>> { Ok(vec![esearch_path(q, m), esummary_path(&[])]) } fn parse_responses(&self, e: &[super::fetch::FetchExchange]) -> crate::Result<ParsedResponse> { if e.len() != 2 { return Err(ScienceError::Invalid("dbsnp: 2 exchanges".into())); } let ids = parse_esearch(&e[0].response)?; if ids.is_empty() { return Err(ScienceError::Invalid("no ids".into())); } parse_esummary(&e[1].response) } }
#[cfg(test)] mod tests { use super::*; const S: &[u8] = br#"{"esearchresult":{"idlist":["12345"]}}"#; const M: &[u8] = br#"{"result":{"uids":["12345"],"12345":{"snp_id":12345,"chr":"7"}}}"#; #[test] fn ok() { let p = parse_esummary(M).unwrap(); assert_eq!(p.records[0].title,"rs12345"); } }
