//! NCBI GEO via E-utilities. Seam: S3. 2-step.
use super::adapter::ProtocolAdapter; use super::fetch::{ParsedResponse, RetrievedRecord}; use crate::ScienceError;
pub fn esearch_path(term: &str, max: u32) -> String { format!("/esearch.fcgi?db=gds&retmode=json&retmax={max}&retstart=0&term={}", super::url_encode(term)) }
pub fn esummary_path(ids: &[String]) -> String { format!("/esummary.fcgi?db=gds&retmode=json&id={}", ids.join(",")) }
fn parse_esearch(bytes: &[u8]) -> crate::Result<Vec<String>> { let v: serde_json::Value = serde_json::from_slice(bytes)?; Ok(v.pointer("/esearchresult/idlist").and_then(|l| l.as_array()).unwrap_or(&super::EMPTY_JSON_ARRAY).iter().filter_map(|i| i.as_str().map(|s| s.to_owned())).collect()) }
fn parse_esummary(bytes: &[u8]) -> crate::Result<ParsedResponse> { let v: serde_json::Value = serde_json::from_slice(bytes)?; let r = v.get("result").ok_or_else(|| ScienceError::Invalid("geo: missing result".into()))?; let uids = r.get("uids").and_then(|u| u.as_array()).ok_or_else(|| ScienceError::Invalid("missing uids".into()))?; let mut recs = Vec::with_capacity(uids.len()); for uid in uids { let uid = uid.as_str().unwrap_or(""); if uid.is_empty() { continue; } if let Some(item) = r.get(uid) { let acc = item.get("accession").and_then(|a| a.as_str()).unwrap_or(uid); let title = item.get("title").and_then(|t| t.as_str()).unwrap_or(""); recs.push(RetrievedRecord { id: uid.to_owned(), title: title.to_owned(), container: item.get("taxon").and_then(|t| t.as_str()).unwrap_or("GEO").to_owned(), url: format!("https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc={acc}") }); } } Ok(ParsedResponse { total_hits: recs.len() as u64, records: recs }) }
pub struct GeoAdapter;
impl ProtocolAdapter for GeoAdapter { fn descriptor(&self) -> &'static super::ConnectorDescriptor { &super::GEO } fn expected_exchanges(&self) -> usize { 2 } fn build_fixture_paths(&self, q: &str, m: u32, _f: &[Vec<u8>]) -> crate::Result<Vec<String>> { Ok(vec![esearch_path(q, m), esummary_path(&[])]) } fn parse_responses(&self, e: &[super::fetch::FetchExchange]) -> crate::Result<ParsedResponse> { if e.len() != 2 { return Err(ScienceError::Invalid("geo: 2 exchanges".into())); } let ids = parse_esearch(&e[0].response)?; if ids.is_empty() { return Err(ScienceError::Invalid("no ids".into())); } parse_esummary(&e[1].response) } }
#[cfg(test)] mod tests { use super::*; const M: &[u8] = br#"{"result":{"uids":["200012345"],"200012345":{"accession":"GSE12345","title":"Gene expression in cancer","taxon":"Homo sapiens"}}}"#; #[test] fn ok() { let p = parse_esummary(M).unwrap(); assert_eq!(p.total_hits,1); } }
